server:
    port: 8080
    servlet:
        context-path: /jodconverter
    compression:
        enable: true #启用GZIP压缩功能
        mime-types: application/javascript,text/css,application/json,application/xml,text/html,text/xml,text/plain,font/woff,application/font-woff,font/eot,image/svg+xml,image/x-icon #压缩格式
        min-response-size: 2048
simText: txt,html,htm,asp,jsp,xml,json,properties,md,gitignore,log,java,py,c,cpp,sql,sh,bat,m,bas,prg,cmd
# 请求的根路径,若为http协议无需更改。若为https协议需修改为全路径(例如：https://dev.youshengyun.com/jodconverter)
base:
    url: default
beian: default
cache:
    clean:
        cron: 0 0 3 * * ?
        enabled: true
    enabled: true
    type: redis    # 缓存类型 jdk/redis
cad:
    preview:
        type: svg
    thread: 5
    timeout: 90
convertMedias: avi,mov,wmv,mkv,3gp,rm
delete:
    captcha: false
    password: 123456
    source:
        file: true
file:
    dir: /jodconverter/file #预览生成资源路径（默认为打包根路径下的file目录下）
    upload:
        disable: false
ftp:
    control:
        encoding: UTF-8
    password: 111111
    username: y9admin
local:
    preview:
        dir: default
media: mp3,wav,mp4,flv
media.convert.disable: false
office:
    documentopenpasswords: true
    exportbookmarks: true
    exportnotes: true
    # home: /opt/openoffice4
    home: /opt/libreoffice7  # Libreoffice/Openoffice  驱动的绝对路径
    maximageresolution: 150
    pagerange: false
    plugin:
        server:
            ports: 2001,2002 # office转换服务的进程数，默认开启两个进程
        task:
            timeout: 5m # office 转换服务 task 超时时间，默认五分钟
    preview:
        switch:
            disabled: false
        type: pdf #office类型文档(word ppt)样式，默认为图片(image)，可配置为pdf（预览时也有按钮切换）
    quality: 80
    type:
        web: web
    watermark: false
pdf: # pdf下 按钮的禁用
    bookmark:
        disable: false
    download:
        disable: false
    openFile:
        disable: false
    presentationMode:
        disable: false
    print:
        disable: false
pdf2jpg:
    dpi: 144
prohibit: exe,dll,dat

spring:
    freemarker: # Freemarker 配置
        cache: false
        charset: UTF-8
        check-template-location: true
        content-type: text/html
        expose-request-attributes: true
        expose-session-attributes: true
        request-context-attribute: request
        suffix: .ftl
        template-loader-path: classpath:/templates/
    redisson:
        address: 127.0.0.1:6379
        password:
        database: 11
    servlet:
        multipart:
            max-file-size: 500MB # 文件上传限制前端
            max-request-size: 500MB #文件上传限制
tif:
    preview:
        type: tif
#信任站点，多个用','隔开，设置了之后，会限制只能预览来自信任站点列表的文件，默认不限制
#trust.host = youshengyun.com
trust:
    host: default
watermark:
    alpha: 0.2
    angle: 10
    color: black
    font: 微软雅黑
    fontsize: 18px
    height: 80
    txt:
    width: 180
    x:
        space: 10
    y:
        space: 10
