MobPush:
    appKey: 2fcd5e3a22ff8
    masterSecret: a1b1325012cd9ba86d48f02332e62bf6
flowable:
    common:
        app:
            idm-url: http://localhost:7056/processAdmin
            tenantId: ""
            idmAdmin:
                user: admin
                password: 111111
hibernate:
    dialect:
        mssql: org.hibernate.dialect.SQLServer2012Dialect
        mysql: org.hibernate.dialect.MySQL8Dialect
        oracle: org.hibernate.dialect.Oracle10gDialect
logging:
    config: classpath:log4j2.xml
management:
    endpoints:
        web:
            exposure:
                include: '*'
mybatis:
    mapper-locations: classpath:/META-INF/modeler-mybatis-mappings/*.xml
server:
    port: 8080
    servlet:
        encoding:
            charset: UTF-8
            enabled: true
            force: true
        session:
            tracking-modes: COOKIE
    tomcat:
        uri-encoding: UTF-8
spring:
    application:
        name: processAdmin
    autoconfigure:
        exclude:
            - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
            - org.springframework.boot.autoconfigure.data.mongo.MongoDataAutoConfiguration
            - org.springframework.boot.autoconfigure.mongo.MongoAutoConfiguration
    cloud:
        nacos:
            config:
                enabled: false
                group: DEFAULT_GROUP
                namespace: dev
                server-addr: https://dev.youshengyun.com:443
                username: nacos
                password: Risesoft@2022
            discovery:
                enabled: false
    config:
        import:
            - optional:nacos:processAdmin.yml
            #- optional:nacos:test01.yml?group=group_02
            #- optional:nacos:test02.yml?group=group_03&refreshEnabled=false
    datasource:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        druid:
            filter:
                stat:
                    log-slow-sql: true
                    mergeSql: true
                    slow-sql-millis: 3000
                wall:
                    config:
                        drop-table-allow: false
                    enabled: true
            stat-view-servlet:
                enabled: false
                url-pattern: /druid/*
                login-username: admin
                login-password: admin
                reset-enable: false
                allow: 127.0.0.1
            web-stat-filter:
                enabled: false
                url-pattern: /*
                exclusions: '*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*,/static/*'
            tenantDefault: spring.datasource.druid.flowable
            y9-public:
                #driver-class-name: oracle.jdbc.OracleDriver
                #url: jdbc:oracle:thin:@127.0.0.1:1521:orcl
                #username: Y9_PUBLIC
                #password: '111111'
                driver-class-name: com.mysql.cj.jdbc.Driver
                url: jdbc:mysql://127.0.0.1:3306/y9_public?serverTimezone=GMT%2B8&nullCatalogMeansCurrent=true&useUnicode=true&characterEncoding=utf-8&rewriteBatchedStatements=true&useCompression=true&useSSL=false&allowPublicKeyRetrieval=true
                username: root
                password: 111111
                initialSize: 1
                maxActive: 20
                maxPoolPreparedStatementPerConnectionSize: 100
                maxWait: 60000
                minEvictableIdleTimeMillis: 300000
                minIdle: 1
                poolPreparedStatements: true
                testOnBorrow: false
                testOnReturn: false
                testWhileIdle: true
                timeBetweenEvictionRunsMillis: 60000
                useGlobalDataSourceStat: true
                validationQuery: SELECT 1 FROM DUAL
            flowable:
                driver-class-name: com.mysql.cj.jdbc.Driver
                url: jdbc:mysql://127.0.0.1:3306/y9_flowable?serverTimezone=GMT%2B8&nullCatalogMeansCurrent=true&useUnicode=true&characterEncoding=utf-8&rewriteBatchedStatements=true&useCompression=true&useSSL=false&allowPublicKeyRetrieval=true
                username: root
                password: 111111
                initialSize: 1
                maxActive: 20
                maxPoolPreparedStatementPerConnectionSize: 100
                maxWait: 60000
                minEvictableIdleTimeMillis: 300000
                minIdle: 1
                poolPreparedStatements: true
                testOnBorrow: false
                testOnReturn: false
                testWhileIdle: true
                timeBetweenEvictionRunsMillis: 60000
                useGlobalDataSourceStat: true
                validationQuery: SELECT 1 FROM DUAL
    jpa:
        generate-ddl: true
        hibernate:
            naming:
                implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyHbmImpl
                physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        open-in-view: false
        properties:
            hibernate:
                cache:
                    use_query_cache: false
                    use_second_level_cache: false
                dialect: org.hibernate.dialect.MySQL8Dialect
                hbm2ddl:
                    auto: update
                jdbc:
                    batch_size: 100
                show_sql: false
    kafka:
        bootstrap-servers: localhost:9092
        consumer:
            auto-commit-interval: 1000
            enable-auto-commit: true
            group-id: y9processAdmin-server
    liquibase:
        change-log: classpath:db/liquibase-changelog.xml
        enabled: true
    main:
        allow-bean-definition-overriding: true
    mvc:
        view:
            prefix: /WEB-INF/jsp/
            suffix: .jsp
    redis:
        database: 8
        host: localhost
        lettuce:
            pool:
                max-active: 8
                max-idle: 8
                max-wait: -1
                min-idle: 0
            shutdown-timeout: 100ms
        password: y9i-83204585
        port: 6379
        ssl: false
        timeout: 10000
    servlet:
        multipart:
            max-file-size: 200MB
            max-request-size: 1000MB
y9:
    systemName: processAdmin
    internalIp: 192.168.x.x,10.0.x.x,172.20.x.x
    app:
        processAdmin:
            cooperationStateSwitch: false
            dataCenterSwitch: false
            entrustSwitch: true
            messagePushSwitch: false
            pushSwitch: false
            smsSwitch: false
            systemCnName: 流程管理器
            systemName: processAdmin
            todoSwitch: false
            weiXinSwitch: false
            weiXinUrl: https://www.youshengyun.com/Youshengyun/Api/pushTempMessage
            imageCountUrl: http://localhost:8081/imageCount
    service:
        itemAdmin:
            directUrl: http://localhost:7056
        datacenter:
            directUrl: http://localhost:7056
        sms:
            directUrl: http://localhost:7056
        todo:
            directUrl: http://localhost:7056
        msgRemind:
            directUrl: http://localhost:7056
        org:
            directUrl: http://localhost:7055
    common:
        cacheEnabled: true
        kafkaEnabled: true
        orgBaseUrl: http://localhost:7055/platform
        processAdminBaseUrl: http://localhost:7056/processAdmin
        itemAdminBaseUrl: http://localhost:7056/itemAdmin
        datacenterBaseUrl: http://localhost:7056/datacenter
        msgRemindBaseUrl: http://localhost:7056/msgRemind
        smsBaseUrl: http://localhost:7056/sms
        todoBaseUrl: http://localhost:7056/todo
        logBaseUrl: http://localhost:7056/log
        userOnlineBaseUrl: http://localhost:7056/userOnline
    feature:
        jpa:
            packagesToScanEntityPublic: net.risesoft.y9public.entity
            packagesToScanEntityTenant: net.risesoft.entity
            packagesToScanRepositoryPublic: net.risesoft.y9public.repository
            packagesToScanRepositoryTenant: net.risesoft.repository
        license:
            publicKey: "30820122300d06092a864886f70d01010105000382010f00303032301006072a8648ce3d02002EC311215SHA512withECDSA106052b81040006031e0004766422ea9a7afb8dae15b491c6ef1e591d9d4bfc992437f82f8a480bG82010a02820101008675a892587630b07efbb4a55d20190348f8ce88b42c311362a4527c6cf0774233b77ef2a50084d3338c76ada1c9039d6935d4bfb635312f5a0d6a700bb2c41745f29bb7ed4f9712fba324bb68cfed5cb38556a7782b795b1243c64a03RSA4204813SHA512withRSA649e6772e14983d65ae7b3bae9fef7f8ff47443e545d4917808946b9a1bdbaf1d8378951f4cfae5c49377b7e92ee7aac300cd204d0f5c0766c8a9800f4f2fb6232c93b68c68c867d1bfe013e2b81f3497f9de02eee384f97cc704800c6a0d32684592ce08087d8619626493ceb1308d61c26a81e703af6a5abffce0d56f11e24dc48b9aaf1277b7181c35bc537fabf47ef756102a14964728ee2b9462cfff4d7a7ed5ddd0203010001"
            internalString: risesoft-youshengyun-y9
            hardwareIdMethod: 0
            productId: risesoft-y9
            productEdition: test
            productVersion: 9.4.0
            licenseFileOnDisk: ${user.home}/y9license.txt
            licenseString: '7e78efc812dada5c29668827783dbee481319d160e7d231bb84f4ad0752ed1e6f794fb15c741021f6a6a42a4ab49541511a775647223a7dadab6126c6e50acc2e4c3a01904a1df2cda6b61cc04a21c4b5af8efc7ac764ec8747d9a237899702a180addda08d49b407fe57d5d2a00011591c8bc8f145bea0947027282513209348eadcbd3718a8c8ddb1b0195f44131bd534fefd105fe5ca246ef9eeb530613ef16f4e00e3d560baead3ed7f141492d586b8b50eb371799ed746d493442a0589fd8e57eadb4a56c451db7c050501a54642d667a9c8d965f6d9469e1f5241e55eb8e0a7834dcf14a304ee3c244d939a8e6fbc8b7a640062dd7e044824978898339979191708409b4d5d43bddfa4dedeacf68437a9f29a4914f4939752fbed2fbfedee9e25c0b57bb04fc9618e88bd18824a2ce7db94bb5999a87b3bda495a3e7bfc03caf1f23798cf68bf6a36dd8a00103897bf6eebc9daf7b87899f1fb04d8961aa02accce671dc9140a11e6f3d8bb45a3b910ebc2e106690b242dfc669ff7bca1be4284c644fba62c1f1a5b7f4043de429e377dbf46b807cb4cda1df32252d8abd55c7b4cab9548e4b868e6ee80ca1e3ad8c61e42afab56730d6a8eff890fadca2e22e9f4a637537ed4c2dc9576948e98228606413ab74c60f0f5d4b9200eb7696e00c2d9c662ea40832ff435b66cb96da68ce2e4ad278e47d895e52e0383e082b926e1aa88545a66fe7440e7d2215b40b35562aa5eea757dc494a436a3e01b80d153543f2cb26da0ab749665e2b7f38fda186faa50f496070e04561a5e459829c69741a75f458789d17709906f541d3280c0dfd42375b86d20f38a46278dd0a0b78828cf941d8485faaca8a1aae9148d273485c8c67087447b450be72952cb9f76905c03684c5f6a39d3d7cd970d5c347241455160b50c7941f9ee1d7c92b406018b3a635c97e699381651784054f26'
        log:
            enabled: true
            # kafka, api
            logSaveTarget: kafka
        session:
            redis:
                enabled: true
                maxInactiveIntervalInSeconds: 3600
        security:
            enabled: true
            cors:
                allowCredentials: true
                allowed-headers: '*'
                allowedOriginPatterns:
                    - https://*.youshengyun.com
                    - http://*.youshengyun.com
                    - https://vue.youshengyun.com:8443
                    - http://localhost:7056
                    - http://localhost:8080
                    - http://localhost:8081
                    - http://127.0.0.1:7056
                    - http://localhost:17056
                    - http://127.0.0.1:17056
            xss:
                ignoreParam:
                    - json_xml
                    - conditionExpression
        oauth2:
            resource:
                enabled: true
                saveLogMessage: false
                saveOnlineMessage: false
                allowBasicAuthentication: true
                allowFormEncodedBodyParameter: true
                allowUriQueryParameter: true
                protectedUrlPatterns: /vue/*,/editor/*,/modeler*
                opaque:
                    client-id: clientid
                    client-secret: secret
                    introspection-uri: http://localhost:7055/sso/oauth2.0/introspect
                    profile-uri: http://localhost:7055/sso/oauth2.0/profile
